### ISSUE TITLE
Questions concerning the example

### ISSUE THREAD

**Issue by P4sca1** [panva/node-openid-client#108]
I'm just getting familiar with oauth 2.0 and open id connect and your libraries (the provider as well as the client) are really helping me to understand the overall flow better and better.

While looking through the provided example, I came across 2 parts that raised some questions which hopefully can get answered:

1) https://github.com/panva/node-openid-client/blob/master/example/app.js#L205-L236
Why is there a GET and a POST route for the callback (which basically do the same), when is which route called and what does the fragment response part mean?

2) https://github.com/panva/node-openid-client/blob/master/example/app.js#L259-L304
This /user route should only be accessible when authenticated, as far as I understood.
Is it correct that the introspect function is used to determine if an access token is still valid? Is this the correct place to refresh access tokens when they got expired? Can't we just use the expiration date of the access token, because making an introspect request every time the user requests the page is kinda expensive, isn't it?

Another thing I still don't get is the purpose of the id token. Why is the user info fetched every time even when there already is an id token? I thought the id token includes the user info? Also what's the purpose of the id token when you could just always call a user API endpoint, that returns the user info based on the access token / session used?

I'm sorry for all this questions, I'm quite new to this topic and tried to understand as much as I can from the openid specs, however it is a massive amount of information and I still don't get some things.
Your example already made some things clear, I hope you can answer some more of my questions.

Thanks in advance,
Pascal

**Comment by panva** [comment]
I'm just going to go ahead and link the relevant specs where possible.

1)
- on (GET) `query` and `fragment` response modes https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#ResponseModes
- on (POST) `form_post` response mode https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html

2) DO NOT use the example app as how an app should be structured and how resources should be protected. Its only purpose is to show the API in use. I intend to remove the example completely because i fear people can take it for a scaffold app, which it isn't by any remote means.

On userinfo/id token, they serve different purposes, id token in its bare form DOES NOT include user claims (unless response_type=id_token), but they are not forbidden which is why many providers tend to include them. ID token in its bare form is a JWT containing information about the authentication that happened (user, when, how, etc). Userinfo on the other hand, well, it's userinfo.

**Comment by P4sca1** [comment]
Another question for the different response_modes, hope it is okay to not open a new issue for this.
Is it okay to use `router.all` to avoid code duplication (the code for `router.post` and `router.get` is the same)?
Also when and why would a client use the fragment response_mode as it is not readable from node.js and requires another step of reposting? The documentation says that it is the default for the code flow, but why not use the query response_mode there?

**Comment by panva** [comment]
Because `fragment` does not leave the browser, hence does not leak the id_token (potentially includes PII) and access token values. `query` is usually logged by every web server.

> Also when and why would a client use the fragment response_mode as it is not readable from node.js 

It would usually use form_post if supported by the OP. but if it is not then fragment is the only way to go for the by far most safest response_type (`code id_token`) => http://openid.net/2016/07/16/preventing-mix-up-attacks-with-openid-connect/

> Is it okay to use router.all

no, you don't want to support PUT and DELETE, do you?
