### ISSUE TITLE
Verify User Question

### ISSUE THREAD

**Issue by douglasrlee** [panva/node-openid-client#19]
So, I do not want to verify my user information and would like to not have to include a user information endpoint in that scenario, is that possible?

I was looking through the source but it looks like it is always required right now.

This is using passport too btw. If I don't do the passport way I can do this.

**Comment by panva** [comment]
Hello @douglasrlee, similar to #18, change your verify fn signature to (tokenset, done) and no userinfo will be called. I thought this fn arity specific returns are common enough in passport.

Can you suggest how to modify the documentation so that it's clear you can do both of the below?
- tokenset, done
- tokenset, userinfo, done

**Comment by douglasrlee** [comment]
@panva that makes sense, but it is the fact that I still have to provide the user info endpoint even if I don't want the user info part in the function signature.

`const MANDATORY = ['authorization_endpoint', 'jwks_uri', 'token_endpoint', 'userinfo_endpoint'];`

**Comment by panva** [comment]
@douglasrlee I see, well, seeing how http://openid.net/specs/openid-connect-discovery-1_0.html says userinfo_endpoint is RECOMMENDED, and an OP can exist that only supports response_type=id_token i'll sort this out.

Until then just put a value in and change your verify arity so that it's not called.

**Comment by panva** [comment]
fixed in [v1.6.2](https://github.com/panva/node-openid-client/blob/master/CHANGELOG.md#version-162)
