### ISSUE TITLE
Not able to use strict cookies for Openid connect auth

### ISSUE THREAD

**Issue by som-nitjsr** [panva/node-openid-client#208]
**Describe the bug**

I have nodejs server app where i want to use openid connect code flow. using passportjs.
for session i am using  I am using expressSession   with **strict** policy cookies.  MY idp is on different domain so it is not able to pass the nonce for validation.

Note: the app works with cookie as **Lax**.

**To Reproduce**
Issuer and Client configuration: (inline or gist) - Don't forget to redact your secrets.
```js
// Issuer configuration (issuer.metadata) and how it is constructed (discovery or manual?)
{
  // ...
}
// Client configuration (client.metadata) and how it is constructed (fromUri or manual?)
{
  // ...
}
```

Steps to reproduce the behaviour:

1.  
2.  
3.  

**Expected behaviour**

**Environment:**
 - openid-client version: [e.g. v2.4.3]
 - node version: [e.g. v8.9.0]

**Additional context**

 - [ ] the bug is happening on latest openid-client too.
 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
well, `strict` won't work - please read up on what the different `sameSite` options mean to the browser cookie jar. This has nothing to do with the library.

**Comment by panva** [comment]
from #209 

> Can you please add support fop storing these variable other than session cookie.

Removing the binding of nonce, state and other parameters to the browser session goes against every best current practice, i don't see why we'd remove that. Cookies are just needed since there's no other mechanism available to do that binding.

Removing state for code flow makes you csrf vulnerable. Removing nonce for id_token flow does the same.

> I still believe the issue is in this library only.

It is not, by setting your session cookie to `strict` and therefore not receiving your cookie on a top level redirect (which you would with `lax`) you're removing one of the prerequisites for a secure oauth2 flow (it says so right in the error message `authentication requires session support`, it is INTENDED).

If you 100% want `strict` cookies, make your callback a self-submitting form rendering html route that takes the parameters and re-post's them to the same route only POST, on which you'll have the strategy callback.

**Comment by som-nitjsr** [comment]
Hi want to implement a BBF approch in node js  and use the session cookie as strict.  same was done in .Net https://brockallen.com/2019/01/11/same-site-cookies-asp-net-core-and-external-authentication-providers/.
here .net uses separate lax cookie for maintaing the  nonce etc and after validation use strict cookie for session.
Is there any suggestion how achieve the same using strict session cookies. 
even i have tried writing post method for sending these parameter s after IDP callback. but since the get request was  from idp domain it create a new session id and we lost the none for validation.

**Comment by panva** [comment]
> even i have tried writing post method for sending these parameter s after IDP callback. but since the get request was from idp domain it create a new session id and we lost the none for validation

Why don’t you configure your session not to do that? i.e. don’t save an empty session or don’t apply the session middleware for that route?

> here .net uses separate lax cookie for maintaing the nonce etc and after validation use strict cookie for session.

You can do that too, the strategy is <200 LOC, inline it.

**Comment by som-nitjsr** [comment]
thanks for the info. 
 i have used  this.app.use(session); in middle ware   how i can skipp session for get method /callback root.
