### ISSUE TITLE
Reopening  https://github.com/panva/node-openid-client/issues/208

### ISSUE THREAD

**Issue by som-nitjsr** [panva/node-openid-client#209]
**Describe the bug**

I still believe the issue is in this library only.
In file https://github.com/panva/node-openid-client/blob/master/lib/passport_strategy.js
**at we are using if (!req.session) {
      throw new TypeError('authentication requires session support');
    }**
and we are storing all the nonce variable in session.
req.session[sessionKey] = pick(params, 'nonce', 'state', 'max_age', 'response_type');
If my i enable strict for my session cookies. these values will not be their when request come back from IDP. because browser will not allow the cookies id.
Can you please add support fop storing these variable other than session cookie.
   let me know if i need to explain a bit more.
**To Reproduce**
Issuer and Client configuration: (inline or gist) - Don't forget to redact your secrets.
```js
// Issuer configuration (issuer.metadata) and how it is constructed (discovery or manual?)
{
  // ...
}
// Client configuration (client.metadata) and how it is constructed (fromUri or manual?)
{
  // ...
}
```

Steps to reproduce the behaviour:

1.  
2.  
3.  

**Expected behaviour**

**Environment:**
 - openid-client version: [e.g. v2.4.3]
 - node version: [e.g. v8.9.0]

**Additional context**

 - [ ] the bug is happening on latest openid-client too.
 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
Removing the binding of nonce, state and other parameters to the browser session goes against every best current practice, i don't see why we'd remove that. Cookies are just needed since there's no other mechanism available to do that binding.

Removing state for code flow makes you csrf vulnerable. Removing nonce for id_token flow does the same.

> I still believe the issue is in this library only.

It is not, by setting your session cookie to `strict` and therefore not receiving your cookie on a top level redirect (which you would with `lax`) you're removing one of the prerequisites for a secure oauth2 flow.

If you 100% want `strict` cookies, make your callback a self-submitting form rendering html route that takes the parameters and re-post's them to the same route only POST, on which you'll have the strategy callback.

**Comment by panva** [comment]
Also, do not "re-open" an issue by creating a new one. You can still comment on closed issues.
