### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by m15ch4** [panva/node-openid-client#210]
Hi guys!

Could you please provide some examples how to use openid-client (especially with Electron).

Thanks.

**Comment by panva** [comment]
> especially with Electron

not gonna go ahead and write a full blown sample but inside electron you should be able to incorporate either of the CLI ready examples

- Using code flow https://gist.github.com/panva/429e0c646eb730079fe0a0070c160e1d
- Using device flow https://gist.github.com/panva/ebaacfe433a8677bdbf458f6e1132045

Both dynamically register a client, that's what you'd usually replace with a static client configuration and you should use [`shell.openItem`](https://electronjs.org/docs/api/shell#shellopenitemfullpath) instead of `open` in electron.

**Comment by hegelstad** [comment]
I have a problem that is not a problem with your library per se, but I would like to know if you can create an example of how to snapshot the current issuer that would be created with Issuer.discover()? The reason I am asking is that I am trying to incorporate this library as a strategy in NestJS's Passport module, but it doesn't play very well with async calls, so I would just like to quickly instantiate issuer once with discover, and then perhaps through serialization, be able to statically recreate that Issuer based on the snapshot.

**Comment by panva** [comment]
@hegelstad docs to the rescue

[`issuer.metadata`](https://github.com/panva/node-openid-client/tree/master/docs#issuermetadata) gives you the metadata that was discovered, you can then do [`new Issuer(metadata)`](https://github.com/panva/node-openid-client/tree/master/docs#new-issuermetadata) with that object. Just mind you that you should not be re-using it forever. At some point a re-discovery might make sense.
