### ISSUE TITLE
Question: how to support both OIDC and OAuth?

### ISSUE THREAD

**Issue by jameskhedley** [panva/node-openid-client#223]
Hi, thanks for the excellent client which we've used to demo a cloud version of a product we have and would love to use it going forward. 

I do have a question though - if it is a requirement to flexibly support both OAuth and OIDC public providers, what is a sensible way to go about it? I realise I can use a different client for OAuth but that would seem to complicate our authentication code.

Am I missing something or are the endpoints basically the same for e.g. Google OIDC and Twitter OAuth? Obviously we lose discovery and probably JWTs with the latter.

One thing that would work is to set something like Keycloak up in our environment and point that at the OAuth providers we need (you can easily configure them in its dashboard) then point `node-openid-client` at the Keycloak instance. Is something similar possible with `node-oidc-provider`? Is there a simpler way?

**Comment by panva** [comment]
@jameskhedley 

Thanks for the kind words. Please consider [supporting](https://github.com/panva/node-openid-client?sponsor=1) the library(ies) if it provides value to you or your company.

As far as I know you can use the client with any oauth service and consume any of the pure OAuth responses so long as you use the `oauthCallback` method rather than `callback` one which handles the extra OIDC bits.

See the description of the `callback` method [documentation](https://github.com/panva/node-openid-client/blob/v3.11.0/docs/README.md#clientcallbackredirecturi-parameters-checks-extras), all the way at the end.

Questions for `oidc-provider` don't belong here.
