### ISSUE TITLE
JWT id_token verification

### ISSUE THREAD

**Issue by victortostes-hotmart** [panva/node-openid-client#285]
I'm trying to verify `id_token` locally on my own middleware lib. It means I don't wanna send a request to my OP to verify token integrity in non critical requests due resilience gurantee even when my OP is out of service; 

I'd like to know if possible to have a public verify method on API just to avoid using other libs to make the verification;

**Comment by panva** [comment]
I'm not going to make those public as there are multiple aspects to verifying tokens that are context specific, that context is something the library knows, an offline process cannot replicate the conditions, the library internally uses [jose](https://github.com/panva/jose), meaning that you can use that one without incurring a "new" dependency since it's already in your dependency tree. Using it you can perform the validation in a way that suits you.

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-openid-client?sponsor=1) the library if it provides value to you or your company. Supporting the library means, amongst other things, that my support and the library itself will be available to you in the future.
