### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by p3pp8** [panva/node-openid-client#309]
Sorry to boring you again, i managed to setup a custom proxy agent and let the flow go ahead till the client.callback function call where i pass the redirect_uri and params(session_state and code) to it to obtain the token and unfortunately this is the result: 

```
{"name":"RequestError","code":"ECONNREFUSED","timings":{"start":1604335021760,"socket":1604335021761,"lookup":1604335021762,"error":1604335023810,"phases":{"wait":1,"dns":1,"total":2050}}}
```

To get more info i've added a hook on the `afterResponse` event and printed out headers and body from response and, surprisingly, discovered that the response body is good and it has the generated access token, so there must be something after receiving the response from the server that is causing the client to raise that exception. Analyzing the headers i've noticed a `connection: 'close'` value set from remote host, but i think it should be normal as connecion is closed after token has been received. Any suggestion is very appreciated! 

Thanx again!

**Comment by panva** [comment]
This is all related to the incomplete proxy setup. Did you also set the proxy up on the `issuer` instance object? 

I'm guessing here since this isn't enough for me to be sure - you're not including any call identifiers, traces or similar.

The client is working with the response it gets from the token endpoint and the first time its about to verify the ID Token it goes and fetches the issuer's `jwks_uri`.

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-openid-client?sponsor=1) the library if it provides value to you or your company and this and the previous support was of help to you. Supporting the library means, amongst other things, that such support will be available to you in the future.
