### ISSUE TITLE
Angular2 Hybrid Flow

### ISSUE THREAD

**Issue by gulatiy** [panva/node-openid-client#33]
Hi @panva, 

I am creating an angular 2 app with hybrid flow authentication,it would be great if you can suggest some ways in which this library can be used to achieve this. Some examples could also be handy. Thanks :-)

**Comment by panva** [comment]
Hey @gulatiy, do you have any particular reason for using Hybrid? I can certainly help or advise but would need more details and insights to do it properly.

**Comment by gulatiy** [comment]
We are using Hybrid Flow to use the features like refresh tokens and it is a combination of both the flows also it is the part of our requirements.
We are building a SPA using Angular 2 and we need some advice setting up this repository with angular 2.

**Comment by panva** [comment]
Hey @gulatiy, that's not really more descriptive ;) But let's see how far we can get.

It is actually rather easy. Basically you must collect the authorization callback params (serialized in fragment on your redirect_uri) and get them (via any means) to your node backend, where you will run the usual `#authorizationCallback()` function of your client. This will run the code flow for the received code as well as validate the tokens in a usual fashion.

It is essential that you forward all received parameters to your backend for validation using openid-client because the id_token may contain claims which can only be validated if the other token values are also present.

If you are using the tokens received in fragment in your SPA right away then please beware that you MUST validate them yourself before use.

**Comment by gulatiy** [comment]
Hi @panva I am a newbie to the security so maybe i was a little brief, thanks for this amazing reply.

I now understand the flow of the process, thanks for your time. :-)
