### ISSUE TITLE
Make TokenSet.expires_in an enumerable attribute

### ISSUE THREAD

**Issue by asong-okta** [panva/node-openid-client#543]
**Describe the bug**
When working with a TokenSet object, `expires_in` attribute is excluded from the `Object.keys` result because it is not marked as enumerable. This means whenever I'm trying to perform any actions on the object that only works on enumerable keys (e.g. [Object.keys](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys), [lodash extend/assignIn](https://lodash.com/docs/4.17.15#assignIn), `expires_in` is excluded from the operation.

Suggested fix is to set `enumerable = true` for `expires_in` inside the [TokenSet constructor](https://github.com/panva/node-openid-client/blob/666e0656da6e1070ee952a19f67a1e6e5f633c4e/lib/token_set.js#L5-L12) to ensure that it shows up during enumeration of the properties.
```diff
  constructor(values) {
    Object.assign(this, values);
    const { constructor, ...properties } = Object.getOwnPropertyDescriptors(
      this.constructor.prototype,
    );
+  properties.expires_in.enumerable = true;

    Object.defineProperties(this, properties);
  }
```

**To Reproduce**

```js
TokenSet {
  access_token: '[REDACTED]'
  expires_at: 1668807414
  expires_in: ƒ expires_in() {\n    return Math.max.apply(null, [this.expires_at - now(), 0]);\n  }
  refresh_token: '[REDACTED]'
  scope: 'profile'
  token_type: 'Bearer'
  claims: ƒ claims() {\n    if (!this.id_token) {\n      throw new TypeError('id_token not present in TokenSet');\n    }\n\n    return JSON.parse(base64url.decode(this.id_token.split('.')[1]));\n  }
  expired: ƒ expired() {\n    return this.expires_in === 0;\n  }
  [[Prototype]]: Object
}

Object.keys(tokenSet)
==> (5) ['access_token', 'expires_at', 'refresh_token', 'scope', 'token_type'] // missing 'expires_in'

_.extend({}, tokenSet)
==> {
  access_token: "[REDACTED]",
  expires_at: 1668807414,
  refresh_token: "[REDACTED]",
  scope: "profile",
  token_type: "Bearer",
} // missing `expires_in`
```

Steps to reproduce the behaviour:

1.  Perform any client operation that will return a TokenSet promise, such as [client.grant](https://github.com/panva/node-openid-client/blob/main/docs/README.md#clientgrantbody-extras) or [client.refresh](https://github.com/panva/node-openid-client/blob/main/docs/README.md#clientrefreshrefreshtoken-extras).
2.  Perform `Object.keys` on the resulting `tokenSet` object

**Expected behaviour**

`expires_in` should be included in the `Object.keys(tokenSet)` result.

**Environment:**
 - openid-client version: 5.1.10
 - node version: 16.15.1

**Additional context**

 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
Hello Angie

I believe you'll have to workaround this particular issue you're facing because the non-enumeration of expires_in is intentional.

Because expires_in is only accurate when the access token response is received the library will convert that into an expires_at timestamp instead. In order to make expires_in accurate in later constructed instances of TokenSet only that expires_at needs to be serialized, hence why expires_in is not enumerable.

I believe I could specify the serialization behaviour by defining a toJSON on the prototype and then make expires_in enumerable. But without knowing how consumers of openid-client do their serialization (ie they could e.g. serialize { ...tokenset } instead) I won't be able to do this without a breaking major version release.
