### ISSUE TITLE
client.register never using registration_endpoint when present within mtls_endpoint_aliases

### ISSUE THREAD

**Issue by ranierimazili** [panva/node-openid-client#544]
Hello, 

I was executing the RP test for Open Banking Brazil and I'm failing on test fapi1-advanced-final-client-brazildcr-happypath-test.
When this test is initialized, it creates a [well-known](https://github.com/panva/node-openid-client/files/10075754/well-known_rp.zip) with two registration_endpoint. The first is on root level and another is inside mtls_endpoint_aliases. They are diferent endpoints.

When calling client.register method, it's always using the registration_endpoint from root level, not considering the mtls_endpoint_aliases.registration_endpoint when ca, key and cert are defined on the client instance.

![image](https://user-images.githubusercontent.com/15436207/203554343-42b01618-4f6b-43f0-ba3e-fd45fb621da0.png)

I think you should change assertIssuerConfiguration to consider mtls_endpoint_aliases.registration_endpoint when ca, key, cert are defined and do the same on url parameter of the register method.

**Comment by panva** [comment]
> When calling client.register method, it's always using the registration_endpoint from root level, not considering the mtls_endpoint_aliases.registration_endpoint when ca, key and cert are defined on the client instance.

The OAuth 2.0 client behaviours have no reason to look up `registration_endpoint` in the `mtls_endpoint_aliases` because the client is not doing mtls based client authentication, neither is the optional initial access token an mtls-sender constrained one.

This makes the use of mTLS purely a transport level requirement in the given ecosystem (ie brazil). As such the ecosystem OPs should just use the mtls endpoint in the top level property.

The certification team [plans to](https://gitlab.com/openid/conformance-suite/-/issues/1041) update the conformance suite's behaviours in the ecosystem-specific tests to reflect this.
