### ISSUE TITLE
Using `authorizationUrl()` in combination with PAR adds too many parameters

### ISSUE THREAD

**Issue by philippederyck** [panva/node-openid-client#677]
**Describe the bug**
When using PAR, the authorization URL should only include a client ID and a reqeust URI. Passing the `request_uri` property into the `authorizationUrl()` function effectively adds this parameter, but all the other authorization code flow parameters also seem to be added. 

The same applies to using JAR with a `request` parameter.

**To Reproduce**
Issuer and Client configuration: (inline or gist) - Don't forget to redact your secrets.
```js
const parResponse = await client.pushedAuthorizationRequest({ ... });
const authzUrl = client.authorizationUrl({request_uri: parResponse.request_uri})
// Result: https://myissuer.com/connect/authorize?client_id=nodejs&scope=openid&response_type=code&redirect_uri=...&request_uri=urn%3Aietf%3Aparams%3Aoauth%3Arequest_uri%3AA4A47EBE522E5FCD5EBDE1DA0336121A395EA542E7D8C76CE66FF517DAA80F85
```

**Expected behaviour**
Detect that PAR is being used and refrain from adding the default request parameters.

**Environment:**
 - openid-client version: 5.6.5
 - node version: v20.11.1

**Additional context**

 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] The documentation explicitly mentions that the `request_uri` should be passed to `authorizationUrl` as a parameter

**Comment by panva** [comment]
@philippederyck thank you for raising this. I have, not that long ago, also looked at this and came to the conclusion that this is merely an optics/ergonomics issue that I cannot change within a semver-minor release. Here's why...

This method serves the following use cases

- regular oauth
- OIDC Passing a Request Object by Value
- OIDC 1.0 Passing a Request Object by Reference
- JAR (as per the IETF RFC)
- PAR (as per the IETF RFC)

Now the first one (regular oauth) obviously needs the parameters.

The OIDC Use Cases are bolted on top of oauth saying that these parameters must be present "so that the request is a valid OAuth 2.0 Authorization Request".

Then comes JAR (and later PAR) which ditches this backwards compatibility with a regular authorization endpoint validation pipeline and says to only require client_id additionally to the request object (or its reference) but is also very clear that parameters outside may be present and that the AS is required to ignore them.

So, this is merely optics.

If you wish to NOT have the parameters present pass their value as `null`, it'll be removed from the return.

**Comment by philippederyck** [comment]
> Then comes JAR (and later PAR) which ditches this backwards compatibility with a regular authorization endpoint validation pipeline and says to only require client_id additionally to the request object (or its reference) but is also very clear that parameters outside may be present and that the AS is required to ignore them.
> 
> So, this is merely optics.

Are you sure? I went looking at the PAR spec, but there is nothing in there that states that if there is a `request_uri` parameter, the other parameters should be ignored. I know that such behavior would make sense, I'm just not sure if implementations will actually follow that ...

Anyway, feel free to close this issue if implementing this is too hard, but I'd love to see some form of support (maybe a new function?) to make this cleanly available
