### ISSUE TITLE
Validating/refresh tokens

### ISSUE THREAD

**Issue by geasi** [panva/node-openid-client#78]
Hi FIlip,

I have a SSO server implemented using oidc-provider and a express.js client using openid-client and passport.
Is there a "best practice" to store and validate the jwt in each request or it is made under the hood?
I want to garantee that the token is valid for each request and refresh the token when necessary. Do you have a recommendation for this too?

Thanks!

**Comment by panva** [comment]
Hi @geasi, unfortunately i have no recommendations, it all depends on how you handle sessions, where do you store them, what kind of validations you wish to do on every request, etc. These can be either "cheap" such as validating the jwt signature and expiration, but maybe also "expensive" when you wanna do introspection as a result of every call since, in the end, only introspection can tell you with 100% accuracy if a given access/refresh token is still valid.

**Comment by geasi** [comment]
Thanks for the fast return!

Right... another question: in the client side I am creating the client object via discovery. How do I access the public certificates (jwks) via the client? Is there a method already implemented for this? I could not find this information and I would like to use then to validate jwt's signature.

Thanks!

**Comment by panva** [comment]
Currently marked as private method there's [`issuer.keystore([reload(boolean)]) # => Promise, resolves to a node-jose keystore`](https://github.com/panva/node-openid-client/blob/master/lib/issuer.js#L97-L118). Else you can always reach out to the jwks_uri and read the json response.
