### ISSUE TITLE
Problem with Azure AD B2C - Well-Known URI

### ISSUE THREAD

**Issue by Mak006** [panva/node-openid-client#80]
When using Azure AD B2C, the structure of the Well-Known URL is something like:

https://login.microsoftonline.com/{}.onmicrosoft.com/v2.0/.well-known/openid-configuration?p={Policy}.  In issurer.js, the ".well-known/openid-configuration" part gets appended even though it is clearly defined in the URL.  Then ends up making the bad request to:

https://login.microsoftonline.com/{}.onmicrosoft.com/v2.0/.well-known/openid-configuration?p={Policy}/.well-known/openid-configuration

**Comment by panva** [comment]
This is VERY unusual.

But looking at the [code](https://github.com/panva/node-openid-client/blob/master/lib/issuer.js#L187-L190) you might be able to do (altho dirty, i know) the following.

```
Issuer.discover('https://login.microsoftonline.com/{}.onmicrosoft.com/v2.0/.well-known/openid-configuration?p={Policy}#/.well-known/openid-configuration'
```

Simply tricking the lib into not appending the well known path. I'll work on refactoring this logic to parse the uri properly and look into the parsed path component instead of the whole string.

**Comment by panva** [comment]
`v1.19.5` now handles off-spec cases like this.
