### ISSUE TITLE
redirect provide additional query string parameters for callback url

### ISSUE THREAD

**Issue by hnafar** [panva/node-openid-client#83]
I am using openid-client with passport on an express app. I would like to provide additional query string params for the call back url as follows:

- GET `/protected/endpoint`
- redirect to `/login/?returnUrl=/protected/endpoint`
- redirectTo `oidc.com/redirect_uri=/login/?returnUrl=%2Fprotected%2Fendpoint`
- sign in
- redirect to `/login/?returnUrl=/protected/endpoint`
- redirec to `/protected/endpoint`

How can I provide a returnUrl parameter with the value coming the request, and have it passed to the issuer and passed back to the application?

**Comment by panva** [comment]
There isn't a standard defined authorization parameter other than "state" that would make it so that the OP would return this value to you. You can define your own state and encode these parameters in it.

https://tools.ietf.org/html/draft-bradley-oauth-jwt-encoded-state defines how an RP might utilize state to encode additional parameters.

To use custom parameters or a custom state pass these as a second argument to your init auth call.

```js
app.get('/auth', function (req, res) {
  const state = 'foobar';
  passport.authenticate('oidc', {
    state,
  })(req, res);
});
```
